### ISSUE TITLE
Create <TextField /> Component

### ISSUE THREAD

**Issue by tko22** [hack4impact-uiuc/bridge#32]
[Design System Link](https://www.notion.so/h4iuiuc/Hack4Impact-s-Design-System-Bridge-40aaae97c71f400084b4bbcc5cd8cdee#f529ec92de354584b6d0e0325c886342)

- TextField
- ~~TextField.Label~~

![image](https://user-images.githubusercontent.com/27740557/81462438-6166af80-9167-11ea-836c-fcf08f3769e2.png)

### Props
- `required`: `required`, `optional`
- `helperText`: str
- `autoComplete`
- `aria-label`
- `placeholder`
- `icon`?

more?

**Comment by jackieo5023** [comment]
I'm thinking this should also include:
* `disabled`
* `valid`

We may want to consider proper validation later, either as part of a form component or within this component - ex. having a user define their own rules (max length of 8 characters) and have the component trigger if it's valid or not, rather than the user writing this logic on their own.

I think we can also create a separate AutoComplete component rather than having it be a prop - similar to https://material-ui.com/components/autocomplete/ and https://ant.design/components/auto-complete/, where it's essentially a wrapper around other text input components.

**Comment by tko22** [comment]
btw in form validation, I wouldn't worry about making the title red - it'll be changed in the design system soon.

I agree with disabled and error props and component trigger user-written rules. no worries if you can't do proper validation rn

Also, I'm thinking we create a Form Component that can encompass the differnet type of 
Form inputs (this included) and then you would put the title.. so this one doesnt need to include title
